use std::fs;
use std::path::PathBuf;

fn scratch(name: &str) -> PathBuf {
    let d = std::env::temp_dir().join(format!("jsdata-it-{}-{name}", std::process::id()));
    let _ = fs::remove_dir_all(&d);
    fs::create_dir_all(&d).unwrap();
    d
}

#[test]
fn end_to_end_build() {
    let d = scratch("e2e");
    fs::create_dir_all(d.join("src/BP/scripts")).unwrap();
    fs::write(
        d.join("src/BP/scripts/main.js"),
        "import x from 'y';\nexport const PASSIVES = {\n  regen: { cost: 1 }, // };\n  haste: { cost: `${2}` },\n};\nconst other = 1;\n",
    )
    .unwrap();
    fs::write(
        d.join("jsdata.cfg"),
        "# demo\nout src/wiki/_wikiData.js\nvar PASSIVES = src/BP/scripts/main.js -> const PASSIVES\nlet PASSIVE_COUNT = Object.keys(PASSIVES).length\n",
    )
    .unwrap();

    let o = jsdata::build(&d.join("jsdata.cfg"), true, None);
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    assert!(o.warnings.is_empty(), "{:?}", o.warnings);
    assert_eq!(o.wrote, Some(true));

    let out = fs::read_to_string(d.join("src/wiki/_wikiData.js")).unwrap();
    assert!(out.contains("export const PASSIVES = {\n  regen: { cost: 1 }, // };\n  haste: { cost: `${2}` },\n};"), "{out}");
    assert!(out.contains("export const PASSIVE_COUNT = Object.keys(PASSIVES).length;"));
    let p = out.find("PASSIVES =").unwrap();
    let c = out.find("PASSIVE_COUNT =").unwrap();
    assert!(p < c, "config order preserved");

    // rebuild: only the timestamp would differ -> no write
    let o2 = jsdata::build(&d.join("jsdata.cfg"), true, None);
    assert_eq!(o2.wrote, Some(false));

    // source change -> rewrite
    fs::write(
        d.join("src/BP/scripts/main.js"),
        "export const PASSIVES = { regen: { cost: 2 } };\n",
    )
    .unwrap();
    let o3 = jsdata::build(&d.join("jsdata.cfg"), true, None);
    assert_eq!(o3.wrote, Some(true));
    let out3 = fs::read_to_string(d.join("src/wiki/_wikiData.js")).unwrap();
    assert!(out3.contains("cost: 2"));
}

#[test]
fn check_mode_writes_nothing_and_warns_tdz() {
    let d = scratch("check");
    fs::write(d.join("a.js"), "const A = 1;\n").unwrap();
    fs::write(
        d.join("jsdata.cfg"),
        "let COUNT = Object.keys(LATER).length\nvar LATER = a.js -> const A\n",
    )
    .unwrap();

    let o = jsdata::build(&d.join("jsdata.cfg"), false, None);
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    assert_eq!(o.warnings.len(), 1, "{:?}", o.warnings);
    assert!(o.warnings[0].contains("TDZ"), "{:?}", o.warnings);
    assert_eq!(o.wrote, None);
    assert!(!d.join("_wikiData.js").exists());
}

#[test]
fn errors_collected_across_entries() {
    let d = scratch("errs");
    fs::write(d.join("ok.js"), "const GOOD = 1;\n").unwrap();
    fs::write(
        d.join("jsdata.cfg"),
        "var A = missing.js -> const A\nvar B = ok.js -> const NOPE\nvar C = ok.js -> const GOOD\n",
    )
    .unwrap();

    let o = jsdata::build(&d.join("jsdata.cfg"), true, None);
    assert_eq!(o.errors.len(), 2, "{:?}", o.errors);
    assert!(o.errors[0].contains("cannot read"), "{:?}", o.errors);
    assert!(o.errors[1].contains("not found"), "{:?}", o.errors);
    assert_eq!(o.wrote, None, "errors must block the write");
    assert!(!d.join("_wikiData.js").exists());
}

#[test]
fn pull_all_merges_projects_namespaced() {
    let d = scratch("pull");
    fs::create_dir_all(d.join("bp/wiki")).unwrap();
    fs::write(
        d.join("bp/wiki/_wikiData.js"),
        "// @generated by jsdata - do not edit.\nexport const PASSIVES = { regen: { cost: 1 } };\nexport const PASSIVE_COUNT = Object.keys(PASSIVES).length;\n",
    )
    .unwrap();
    fs::create_dir_all(d.join("boss/wiki")).unwrap();
    fs::write(d.join("boss/wiki/_wikiData.js"), "export const BOSS = { hp: 300 };\n").unwrap();
    fs::write(
        d.join("all.cfg"),
        "out site/_all.js\nvars betterPotions <-- bp --> wiki/_wikiData.js\nvars boss <-- boss --> wiki/_wikiData.js\n",
    )
    .unwrap();

    let o = jsdata::pull_all(&d.join("all.cfg"), true, None);
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    assert_eq!(o.wrote, Some(true));

    let out = fs::read_to_string(d.join("site/_all.js")).unwrap();
    assert!(out.contains("export const betterPotions = (() => {"), "{out}");
    assert!(out.contains("const PASSIVES = { regen: { cost: 1 } };"), "{out}");
    assert!(out.contains("const PASSIVE_COUNT = Object.keys(PASSIVES).length;"), "{out}");
    assert!(out.contains("return { PASSIVES, PASSIVE_COUNT };"), "{out}");
    assert!(out.contains("export const boss = (() => {"), "{out}");
    assert!(out.contains("return { BOSS };"), "{out}");
    assert!(out.find("betterPotions").unwrap() < out.find("export const boss").unwrap());

    // idempotent: only the timestamp would differ -> no rewrite
    let o2 = jsdata::pull_all(&d.join("all.cfg"), true, None);
    assert_eq!(o2.wrote, Some(false));
}

#[test]
fn build_with_markdown_raw_and_html() {
    let d = scratch("md");
    fs::create_dir_all(d.join("docs")).unwrap();
    fs::write(d.join("docs/guide.md"), "# Guide\n\nUse **potions** wisely.\n").unwrap();
    fs::write(
        d.join("jsdata.cfg"),
        "out _wikiData.js\nmd GUIDE_MD <-- docs/guide.md\nmd GUIDE_HTML <-- docs/guide.md <-- html\n",
    )
    .unwrap();

    let o = jsdata::build(&d.join("jsdata.cfg"), true, None);
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    assert_eq!(o.wrote, Some(true));

    let out = fs::read_to_string(d.join("_wikiData.js")).unwrap();
    // raw markdown: kept verbatim, newlines escaped into a one-line JS string
    assert!(out.contains(r##"export const GUIDE_MD = "# Guide\n\nUse **potions** wisely.\n";"##), "{out}");
    // html: converted, tags present, quotes/newlines escaped
    assert!(out.contains("export const GUIDE_HTML = \""), "{out}");
    assert!(out.contains("<h1>Guide</h1>"), "{out}");
    assert!(out.contains("<strong>potions</strong>"), "{out}");
}

#[test]
fn build_single_project_with_var_let_and_langs() {
    // this is what `--pull` runs: a normal config that also carries `langs`
    let d = scratch("pullbuild");
    fs::create_dir_all(d.join("bp/scripts")).unwrap();
    fs::write(d.join("bp/scripts/main.js"), "export const PASSIVES = { a: 1, b: 2 };\n").unwrap();
    fs::create_dir_all(d.join("texts")).unwrap();
    fs::write(d.join("texts/languages.json"), "[\"en_US\"]").unwrap();
    fs::write(d.join("texts/en_US.lang"), "rrs.rarity.common=§7§lCommon\n").unwrap();
    fs::write(
        d.join("jsdata.cfg"),
        "out _wikiData.js\nvar PASSIVES = bp/scripts/main.js -> const PASSIVES\nlet COUNT = Object.keys(PASSIVES).length\nlangs <-- texts <-- texts/languages.json\n",
    )
    .unwrap();

    let o = jsdata::build(&d.join("jsdata.cfg"), true, None);
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    assert_eq!(o.wrote, Some(true));

    let out = fs::read_to_string(d.join("_wikiData.js")).unwrap();
    assert!(out.contains("export const PASSIVES = { a: 1, b: 2 };"), "{out}");
    assert!(out.contains("export const COUNT = Object.keys(PASSIVES).length;"), "{out}");
    assert!(out.contains("export const langs = {"), "{out}");
    assert!(out.contains("  en_US: {"), "{out}");
    assert!(out.contains("\"rrs.rarity.common\": \"§7§lCommon\","), "{out}");
    // config order preserved: PASSIVES, COUNT, langs
    let (p, c, l) = (
        out.find("const PASSIVES").unwrap(),
        out.find("const COUNT").unwrap(),
        out.find("const langs").unwrap(),
    );
    assert!(p < c && c < l, "{out}");
}

#[test]
fn pull_langs_bundle_from_languages_json() {
    let d = scratch("langs");
    fs::create_dir_all(d.join("texts")).unwrap();
    fs::write(d.join("texts/languages.json"), "[\n  \"en_US\",\n  \"ar_SA\",\n  \"missing_XX\"\n]").unwrap();
    fs::write(
        d.join("texts/en_US.lang"),
        "pack.name=Rarity & Stats\n\n## tiers\nrrs.rarity.common=§7§lCommon\nrrs.rarity.rare=§9§lRare\n",
    )
    .unwrap();
    fs::write(d.join("texts/ar_SA.lang"), "pack.name=الندرة\n").unwrap();
    // missing_XX.lang deliberately absent -> warning, skipped
    fs::write(d.join("all.cfg"), "out _all.js\nlangs <-- texts <-- texts/languages.json\n").unwrap();

    let o = jsdata::pull_all(&d.join("all.cfg"), true, None);
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    assert_eq!(o.wrote, Some(true));
    assert!(o.warnings.iter().any(|w| w.contains("missing_XX")), "{:?}", o.warnings);

    let out = fs::read_to_string(d.join("_all.js")).unwrap();
    assert!(out.contains("export const langs = {"), "{out}");
    assert!(out.contains("  en_US: {"), "{out}");
    assert!(out.contains("\"rrs.rarity.common\": \"§7§lCommon\","), "{out}");
    assert!(out.contains("\"pack.name\": \"Rarity & Stats\","), "{out}");
    assert!(out.contains("  ar_SA: {"), "{out}");
    assert!(out.contains("الندرة"), "{out}");
    assert!(!out.contains("missing_XX"), "absent locale omitted: {out}");
}

// A source whose PASSIVES gains `ascended` only at version 2.1.
const VERSIONED_SRC: &str =
    "export const PASSIVES = {\n  regen: 1,\n  //version 2.1 *\n  ascended: 5,\n  //version 2.1 *\n};\n";

#[test]
fn version_directive_and_command_override() {
    let d = scratch("ver");
    fs::create_dir_all(d.join("src")).unwrap();
    fs::write(d.join("src/main.js"), VERSIONED_SRC).unwrap();
    // cfg pins 2.0 (live version); 2.1 content must be filtered out
    fs::write(
        d.join("jsdata.cfg"),
        "out _wikiData.js\nversion 2.0\nvar PASSIVES = src/main.js -> const PASSIVES\n",
    )
    .unwrap();

    // config `version 2.0` → ascended stripped
    let o = jsdata::build(&d.join("jsdata.cfg"), true, None);
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    let out = fs::read_to_string(d.join("_wikiData.js")).unwrap();
    assert!(out.contains("regen: 1"), "{out}");
    assert!(!out.contains("ascended"), "2.0 build must drop 2.1 content: {out}");

    // command `-v 2.1` overrides the cfg directive → ascended kept
    let o2 = jsdata::build(&d.join("jsdata.cfg"), true, Some("2.1"));
    assert!(o2.errors.is_empty(), "{:?}", o2.errors);
    let out2 = fs::read_to_string(d.join("_wikiData.js")).unwrap();
    assert!(out2.contains("ascended: 5"), "-v overrides cfg version: {out2}");
}

#[test]
fn per_directive_pin_beats_command() {
    let d = scratch("verpin");
    fs::create_dir_all(d.join("src")).unwrap();
    fs::write(d.join("src/main.js"), VERSIONED_SRC).unwrap();
    // the var is pinned to 2.1 via `--- 2.1`; a command -v 2.0 must NOT lower it
    fs::write(
        d.join("jsdata.cfg"),
        "out _wikiData.js\nvar PASSIVES = src/main.js -> const PASSIVES --- 2.1\n",
    )
    .unwrap();

    let o = jsdata::build(&d.join("jsdata.cfg"), true, Some("2.0"));
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    let out = fs::read_to_string(d.join("_wikiData.js")).unwrap();
    assert!(out.contains("ascended: 5"), "pin `--- 2.1` beats -v 2.0: {out}");
}

#[test]
fn pull_all_hybrid_per_project_version() {
    // --pull-all -v 2.0, but RarityStats pinned to 2.1 via `--- 2.1`
    let d = scratch("verhybrid");
    for proj in ["RarityStats", "OtherAddon"] {
        fs::create_dir_all(d.join(proj).join("src")).unwrap();
        fs::write(d.join(proj).join("src/main.js"), VERSIONED_SRC).unwrap();
        fs::write(
            d.join(proj).join("jsdata.cfg"),
            "out _wikiData.js\nvar PASSIVES = src/main.js -> const PASSIVES\n",
        )
        .unwrap();
    }
    fs::write(
        d.join("all.cfg"),
        "out site/_all.js\nvars RarityStats <-- RarityStats <-- jsdata.cfg --- 2.1\nvars OtherAddon <-- OtherAddon <-- jsdata.cfg\n",
    )
    .unwrap();

    let o = jsdata::pull_all(&d.join("all.cfg"), true, Some("2.0"));
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    let out = fs::read_to_string(d.join("site/_all.js")).unwrap();
    // RarityStats (pinned 2.1) keeps ascended; OtherAddon (global 2.0) drops it
    let rarity = &out[out.find("RarityStats").unwrap()..out.find("OtherAddon").unwrap()];
    let other = &out[out.find("OtherAddon").unwrap()..];
    assert!(rarity.contains("ascended: 5"), "pinned project at 2.1: {rarity}");
    assert!(!other.contains("ascended"), "global 2.0 project drops 2.1: {other}");
}

#[test]
fn pull_all_per_project_pin_beats_the_global_version() {
    // `--version 2.0` globally, with `--- 2.1` pinning one addon on its `vars`
    // line — the replacement for the old `-v PROJECT=SPEC` flag.
    let d = scratch("vercli");
    for proj in ["RarityStats", "OtherAddon"] {
        fs::create_dir_all(d.join(proj).join("src")).unwrap();
        fs::write(d.join(proj).join("src/main.js"), VERSIONED_SRC).unwrap();
        fs::write(
            d.join(proj).join("jsdata.cfg"),
            "out _wikiData.js\nvar PASSIVES = src/main.js -> const PASSIVES\n",
        )
        .unwrap();
    }
    fs::write(
        d.join("all.cfg"),
        "out site/_all.js\nvars RarityStats <-- RarityStats <-- jsdata.cfg --- 2.1\nvars OtherAddon <-- OtherAddon <-- jsdata.cfg\n",
    )
    .unwrap();

    let o = jsdata::pull_all(&d.join("all.cfg"), true, Some("2.0"));
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    let out = fs::read_to_string(d.join("site/_all.js")).unwrap();
    let rarity = &out[out.find("RarityStats").unwrap()..out.find("OtherAddon").unwrap()];
    let other = &out[out.find("OtherAddon").unwrap()..];
    assert!(rarity.contains("ascended: 5"), "vars pin 2.1: {rarity}");
    assert!(!other.contains("ascended"), "global 2.0: {other}");
}

#[test]
fn pin_on_file_form_is_a_parse_error() {
    let d = scratch("verfileerr");
    fs::create_dir_all(d.join("bp")).unwrap();
    fs::write(d.join("bp/_wikiData.js"), "export const X = 1;\n").unwrap();
    fs::write(
        d.join("all.cfg"),
        "out _all.js\nvars bp <-- bp --> _wikiData.js --- 2.1\n",
    )
    .unwrap();
    let o = jsdata::pull_all(&d.join("all.cfg"), true, None);
    assert_eq!(o.errors.len(), 1, "{:?}", o.errors);
    assert!(o.errors[0].contains("--- <version>"), "{:?}", o.errors);
}

#[test]
fn pull_all_builds_project_from_config() {
    let d = scratch("pullcfg");
    // a project with its OWN jsdata.cfg + source (no pre-generated _wikiData.js)
    fs::create_dir_all(d.join("bp/scripts")).unwrap();
    fs::write(
        d.join("bp/scripts/main.js"),
        "export const PASSIVES = { a: 1, b: 2 };\n",
    )
    .unwrap();
    fs::write(
        d.join("bp/jsdata.cfg"),
        "out _wikiData.js\nvar PASSIVES = scripts/main.js -> const PASSIVES\nlet COUNT = Object.keys(PASSIVES).length\n",
    )
    .unwrap();
    // merge config points at the project's CONFIG (<--), not a generated file
    fs::write(
        d.join("all.cfg"),
        "out site/_all.js\nvars betterPotions <-- bp <-- jsdata.cfg\n",
    )
    .unwrap();

    let o = jsdata::pull_all(&d.join("all.cfg"), true, None);
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    assert_eq!(o.wrote, Some(true));

    let out = fs::read_to_string(d.join("site/_all.js")).unwrap();
    assert!(out.contains("export const betterPotions = (() => {"), "{out}");
    assert!(out.contains("const PASSIVES = { a: 1, b: 2 };"), "{out}");
    assert!(out.contains("const COUNT = Object.keys(PASSIVES).length;"), "{out}");
    assert!(out.contains("return { PASSIVES, COUNT };"), "{out}");
    // building from config must NOT write the project's own _wikiData.js
    assert!(!d.join("bp/_wikiData.js").exists(), "config form is in-memory only");
}

#[test]
fn pull_all_from_config_surfaces_project_errors() {
    let d = scratch("pullcfgerr");
    fs::create_dir_all(d.join("bp")).unwrap();
    fs::write(d.join("bp/jsdata.cfg"), "var X = missing.js -> const X\n").unwrap();
    fs::write(d.join("all.cfg"), "out _all.js\nvars bp <-- bp <-- jsdata.cfg\n").unwrap();

    let o = jsdata::pull_all(&d.join("all.cfg"), true, None);
    assert_eq!(o.errors.len(), 1, "{:?}", o.errors);
    assert!(o.errors[0].contains("bp:") && o.errors[0].contains("cannot read"), "{:?}", o.errors);
    assert_eq!(o.wrote, None);
}

#[test]
fn pull_all_check_reports_missing_and_writes_nothing() {
    let d = scratch("pullerr");
    fs::write(d.join("all.cfg"), "out _all.js\nvars missing <-- nope --> _wikiData.js\n").unwrap();
    let o = jsdata::pull_all(&d.join("all.cfg"), false, None); // --check
    assert_eq!(o.errors.len(), 1, "{:?}", o.errors);
    assert!(o.errors[0].contains("cannot read"), "{:?}", o.errors);
    assert_eq!(o.wrote, None);
    assert!(!d.join("_all.js").exists());
}

#[test]
fn default_out_and_default_config_name() {
    let d = scratch("defaults");
    fs::write(d.join("a.js"), "const A = [1, 2];\n").unwrap();
    fs::write(d.join("jsdata.cfg"), "var A = a.js -> const A\n").unwrap();
    let o = jsdata::build(&d.join("jsdata.cfg"), true, None);
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    assert!(d.join("_wikiData.js").exists(), "defaults next to the config");
}

/// The full version/tag precedence chain, end to end: pin > CLI > config, with
/// the two halves resolving independently.
#[test]
fn version_and_tag_precedence() {
    use jsdata::version::VersionSpec;

    let d = scratch("vtags");
    fs::create_dir_all(d.join("src")).unwrap();
    // TAGGED has one block per tag; UNTAGGED content is always kept.
    let src = "export const A = {\n  base: 0,\n  //version 2.1 [beta]*\n  beta: 1,\n  //version 2.1 [beta]*\n  //version 2.1 [ui]*\n  ui: 2,\n  //version 2.1 [ui]*\n  //version 2.9 *\n  future: 3,\n  //version 2.9 *\n};\n";
    fs::write(d.join("src/a.js"), src).unwrap();
    let cfg = d.join("jsdata.cfg");
    let out = d.join("_wikiData.js");
    let read = || fs::read_to_string(&out).unwrap();

    // 1. Config defaults apply.
    fs::write(
        &cfg,
        "version = 2.5\nversionTags = [beta]\nvar A = src/a.js -> const A\n",
    )
    .unwrap();
    assert!(jsdata::build(&cfg, true, None).errors.is_empty());
    let js = read();
    assert!(js.contains("base: 0") && js.contains("beta: 1"), "{js}");
    assert!(!js.contains("ui: 2"), "tag filter ignored: {js}");
    assert!(!js.contains("future: 3"), "version bound ignored: {js}");

    // 2. CLI overrides the config, per half. --tag ui alone must not disturb
    //    the config's version bound.
    let opts = jsdata::Options {
        version: VersionSpec {
            spec: None,
            tags: Some(vec!["ui".into()]),
        },
    };
    assert!(jsdata::build_with(&cfg, true, &opts).errors.is_empty());
    let js = read();
    assert!(js.contains("ui: 2") && !js.contains("beta: 1"), "{js}");
    assert!(!js.contains("future: 3"), "config version lost: {js}");

    // 3. A pin beats both — and a pin naming no tags still inherits them.
    fs::write(
        &cfg,
        "version = 2.5\nversionTags = [beta]\nvar A = src/a.js -> const A --- 2.9\n",
    )
    .unwrap();
    assert!(jsdata::build(&cfg, true, None).errors.is_empty());
    let js = read();
    assert!(js.contains("future: 3"), "pin version not applied: {js}");
    assert!(js.contains("beta: 1"), "pin dropped inherited tags: {js}");
    assert!(!js.contains("ui: 2"), "{js}");

    // 4. `[]` on a pin means "no tags active here", overriding the inherited
    //    `versionTags` — tags are opt-in, so every tagged block is skipped.
    fs::write(
        &cfg,
        "version = 2.5\nversionTags = [beta]\nvar A = src/a.js -> const A --- 2.5 []\n",
    )
    .unwrap();
    assert!(jsdata::build(&cfg, true, None).errors.is_empty());
    let js = read();
    assert!(js.contains("base: 0"), "{js}");
    assert!(!js.contains("beta: 1") && !js.contains("ui: 2"), "{js}");

    // 5. `[*]` is how you ask for every tag.
    fs::write(
        &cfg,
        "version = 2.5\nversionTags = [beta]\nvar A = src/a.js -> const A --- 2.5 [*]\n",
    )
    .unwrap();
    assert!(jsdata::build(&cfg, true, None).errors.is_empty());
    let js = read();
    assert!(js.contains("beta: 1") && js.contains("ui: 2"), "{js}");
    assert!(!js.contains("future: 3"), "pin version ignored: {js}");

    let _ = fs::remove_dir_all(&d);
}

/// Duplicate declarations of one `const`, each behind its own version block:
/// the newest **valid** one must win at every version.
#[test]
fn duplicate_declarations_resolve_by_version() {
    let d = scratch("dupdecl");
    fs::create_dir_all(d.join("src")).unwrap();
    fs::write(
        d.join("src/c.js"),
        concat!(
            "//version 1.0 1.5 *\nexport const C = { a: 1 };\n//version 1.0 1.5 *\n",
            "//version 1.5 2.0 *\nexport const C = { a: 1, b: 2 };\n//version 1.5 2.0 *\n",
            "//version 2.0 *\nexport const C = { a: 1, b: 2, c: 3 };\n//version 2.0 *\n",
        ),
    )
    .unwrap();
    let cfg = d.join("jsdata.cfg");
    fs::write(&cfg, "var C = src/c.js -> const C\n").unwrap();
    let out = d.join("_wikiData.js");

    for (spec, expect) in [
        ("1.2", "{ a: 1 }"),
        ("1.7", "{ a: 1, b: 2 }"),
        ("2.5", "{ a: 1, b: 2, c: 3 }"),
    ] {
        let o = jsdata::build(&cfg, true, Some(spec));
        assert!(o.errors.is_empty(), "{spec}: {:?}", o.errors);
        let js = fs::read_to_string(&out).unwrap();
        assert!(js.contains(expect), "at {spec} expected {expect}, got:\n{js}");
    }

    // No version at all: everything is valid, so the newest still wins — an
    // unset version means "latest", not "whichever was written first".
    let o = jsdata::build(&cfg, true, None);
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    let js = fs::read_to_string(&out).unwrap();
    assert!(js.contains("{ a: 1, b: 2, c: 3 }"), "unfiltered:\n{js}");

    // Below every block nothing is valid — skipped with a warning, not fatal.
    let o = jsdata::build(&cfg, true, Some("0.9"));
    assert!(o.errors.is_empty(), "should not fail: {:?}", o.errors);
    assert!(
        o.warnings.iter().any(|w| w.contains("C") && w.contains("skipped")),
        "{:?}",
        o.warnings
    );
    let js = fs::read_to_string(&out).unwrap();
    assert!(!js.contains("export const C"), "skipped entry emitted:
{js}");

    let _ = fs::remove_dir_all(&d);
}

/// Nested markers inside the chosen declaration must still be resolved — the
/// picker selects *which* declaration, the filter cleans up *inside* it.
#[test]
fn the_chosen_declaration_is_still_filtered_inside() {
    let d = scratch("dupnested");
    fs::create_dir_all(d.join("src")).unwrap();
    fs::write(
        d.join("src/c.js"),
        concat!(
            "//version 1.0 2.0 *\nexport const C = { old: true };\n//version 1.0 2.0 *\n",
            "//version 2.0 *\n",
            "export const C = {\n  a: 1,\n  //version 2.5 *\n  b: 2,\n  //version 2.5 *\n};\n",
            "//version 2.0 *\n",
        ),
    )
    .unwrap();
    let cfg = d.join("jsdata.cfg");
    fs::write(&cfg, "var C = src/c.js -> const C\n").unwrap();
    let out = d.join("_wikiData.js");

    jsdata::build(&cfg, true, Some("2.2"));
    let js = fs::read_to_string(&out).unwrap();
    assert!(js.contains("a: 1") && !js.contains("old"), "{js}");
    assert!(!js.contains("b: 2"), "nested 2.5 block survived at 2.2:\n{js}");

    jsdata::build(&cfg, true, Some("2.5"));
    let js = fs::read_to_string(&out).unwrap();
    assert!(js.contains("b: 2"), "nested block missing at 2.5:\n{js}");

    let _ = fs::remove_dir_all(&d);
}

/// A declaration absent at the requested version is skipped with a warning, not
/// an error — one missing entry must not fail a whole build.
#[test]
fn absent_at_version_is_skipped_not_fatal() {
    let d = scratch("skipver");
    fs::create_dir_all(d.join("src")).unwrap();
    fs::write(
        d.join("src/a.js"),
        "export const ALWAYS = { a: 1 };\n//version 2.4 *\nexport const LATER = { b: 2 };\n//version 2.4 *\n",
    )
    .unwrap();
    let cfg = d.join("jsdata.cfg");
    fs::write(
        &cfg,
        "var ALWAYS = src/a.js -> const ALWAYS\nvar LATER = src/a.js -> const LATER\nlet COUNT = Object.keys(LATER).length\n",
    )
    .unwrap();

    let o = jsdata::build(&cfg, true, Some("2.0"));
    assert!(o.errors.is_empty(), "should not fail: {:?}", o.errors);
    assert_eq!(o.wrote, Some(true));
    assert!(
        o.warnings.iter().any(|w| w.contains("LATER") && w.contains("skipped")),
        "{:?}",
        o.warnings
    );
    // A `let` naming a skipped entry goes too — otherwise the module throws.
    assert!(
        o.warnings.iter().any(|w| w.contains("COUNT") && w.contains("references skipped")),
        "{:?}",
        o.warnings
    );

    // Skipped entries are silent in the output — no `undefined` placeholder.
    let js = fs::read_to_string(d.join("_wikiData.js")).unwrap();
    assert!(js.contains("ALWAYS"), "{js}");
    assert!(!js.contains("LATER"), "{js}");
    assert!(!js.contains("COUNT"), "{js}");
    assert!(!js.contains("undefined"), "{js}");

    // At 2.5 everything is back.
    let o = jsdata::build(&cfg, true, Some("2.5"));
    assert!(o.errors.is_empty(), "{:?}", o.errors);
    let js = fs::read_to_string(d.join("_wikiData.js")).unwrap();
    assert!(js.contains("LATER") && js.contains("COUNT"), "{js}");

    let _ = fs::remove_dir_all(&d);
}

/// A name that exists at *no* version is a config typo, and stays fatal.
#[test]
fn a_name_declared_nowhere_is_still_an_error() {
    let d = scratch("typo");
    fs::create_dir_all(d.join("src")).unwrap();
    fs::write(d.join("src/a.js"), "export const REAL = 1;\n").unwrap();
    let cfg = d.join("jsdata.cfg");
    fs::write(&cfg, "var X = src/a.js -> const NOSUCHTHING\n").unwrap();

    let o = jsdata::build(&cfg, true, Some("2.0"));
    assert_eq!(o.errors.len(), 1, "{:?}", o.errors);
    assert!(o.errors[0].contains("at any version"), "{:?}", o.errors);
    assert_eq!(o.wrote, None, "errors still block the write");

    let _ = fs::remove_dir_all(&d);
}

/// Markers *inside* one declaration make versions too — a list that grows an
/// entry shouldn't have to duplicate the whole literal.
#[test]
fn in_block_markers_version_a_single_declaration() {
    let d = scratch("inblock");
    fs::create_dir_all(d.join("src")).unwrap();
    fs::write(
        d.join("src/a.js"),
        concat!(
            "export const LIST = [\n",
            "  { id: \"a\" },\n",
            "  //version 2.0 *\n",
            "  { id: \"b\" },\n",
            "  //version 2.0 *\n",
            "  //version 2.5 *\n",
            "  { id: \"c\" },\n",
            "  //version 2.5 *\n",
            "];\n",
        ),
    )
    .unwrap();
    let cfg = d.join("jsdata.cfg");
    fs::write(&cfg, "var LIST = src/a.js -> const LIST\n").unwrap();
    let out = d.join("_wikiData.js");

    for (spec, items) in [("1.0", 1), ("2.0", 2), ("2.5", 3)] {
        jsdata::build(&cfg, true, Some(spec));
        let js = fs::read_to_string(&out).unwrap();
        let got = js.matches("id:").count();
        assert_eq!(got, items, "at {spec} expected {items} items:\n{js}");
    }

    // …and the report lists each version, marking the one in force.
    let opts = jsdata::Options {
        version: jsdata::version::VersionSpec::from_spec("2.0"),
    };
    let report = jsdata::structure::report(&cfg, &opts, false).unwrap();
    assert!(report.contains("3 versions"), "{report}");
    assert!(report.contains("base"), "{report}");
    assert!(
        report.lines().any(|l| l.contains("-> 2.0")),
        "selection not marked:\n{report}"
    );

    let _ = fs::remove_dir_all(&d);
}
