//! Renders the generated module and writes it atomically, skipping the
//! write when nothing but the timestamp would change (so watch-mode no-ops
//! don't trigger downstream rebuilds).

use std::fs;
use std::io;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

/// Render the module. `entries` are `(name, js)` in config order.
pub fn render(config_display: &str, entries: &[(String, String)]) -> String {
    let mut s = String::new();
    s.push_str("// @generated by jsdata - do not edit.\n");
    s.push_str(&format!("// config: {config_display}\n"));
    s.push_str(&format!("// built: {}\n\n", now_iso()));
    for (name, js) in entries {
        s.push_str(&format!("export const {name} = {js};\n"));
    }
    s
}

/// A project's exports re-nested as an IIFE expression `(() => { … })()` for a
/// `--pull-all` merge. The IIFE (not a bare object literal) keeps intra-project
/// references — `Object.keys(PASSIVES)` still resolves once `PASSIVES` is a
/// local binding rather than a stripped-away top-level export. No trailing `;`
/// — [`render`] adds it. `vars` are `(name, verbatim-js)` in order.
pub fn render_project_iife(vars: &[(String, String)]) -> String {
    let mut s = String::from("(() => {\n");
    for (v, js) in vars {
        // ponytail: js emitted verbatim, not re-indented — valid, just not pretty
        s.push_str(&format!("  const {v} = {js};\n"));
    }
    let keys = vars
        .iter()
        .map(|(v, _)| v.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    s.push_str(&format!("  return {{ {keys} }};\n}})()"));
    s
}

/// A `{ locale: { "key": "value" } }` object literal for a `langs` bundle.
/// Locale codes are bare (all valid identifiers); keys/values JSON-escaped,
/// UTF-8 literal. No trailing `;` — [`render`] adds it.
pub fn render_langs_object(locales: &[(String, Vec<(String, String)>)]) -> String {
    let mut s = String::from("{\n");
    for (loc, pairs) in locales {
        s.push_str(&format!("  {loc}: {{\n"));
        for (k, v) in pairs {
            s.push_str(&format!("    {}: {},\n", json_str(k), json_str(v)));
        }
        s.push_str("  },\n");
    }
    s.push('}');
    s
}

/// Minimal JSON/JS double-quoted string. `§` (U+00A7) and other non-control
/// chars pass through literally — the file is UTF-8. Used for lang values and
/// for `md` file contents (newlines become `\n`, so the value stays one line).
pub(crate) fn json_str(s: &str) -> String {
    let mut o = String::with_capacity(s.len() + 2);
    o.push('"');
    for c in s.chars() {
        match c {
            '"' => o.push_str("\\\""),
            '\\' => o.push_str("\\\\"),
            '\n' => o.push_str("\\n"),
            '\r' => o.push_str("\\r"),
            '\t' => o.push_str("\\t"),
            c if (c as u32) < 0x20 => o.push_str(&format!("\\u{:04x}", c as u32)),
            c => o.push(c),
        }
    }
    o.push('"');
    o
}

/// Content equality ignoring the `// built:` timestamp line.
fn same_ignoring_timestamp(a: &str, b: &str) -> bool {
    // drop only the FIRST such line — the header's; a verbatim body line
    // that happens to start with `// built:` must still count as a change
    let strip = |t: &str| {
        let mut dropped = false;
        t.lines()
            .filter(|l| {
                if !dropped && l.starts_with("// built:") {
                    dropped = true;
                    return false;
                }
                true
            })
            .collect::<Vec<_>>()
            .join("\n")
    };
    strip(a) == strip(b)
}

/// Atomic write via temp file + rename. Returns `false` (and writes nothing)
/// when the existing file already matches.
pub fn write_if_changed(path: &Path, content: &str) -> io::Result<bool> {
    if let Ok(old) = fs::read_to_string(path) {
        if same_ignoring_timestamp(&old, content) {
            return Ok(false);
        }
    }
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)?;
        }
    }
    let mut tmp = path.as_os_str().to_owned();
    tmp.push(".tmp");
    let tmp = Path::new(&tmp);
    fs::write(tmp, content)?;
    fs::rename(tmp, path)?; // std rename replaces the target, also on Windows
    Ok(true)
}

fn now_iso() -> String {
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let (h, m, s) = ((secs / 3600) % 24, (secs / 60) % 60, secs % 60);
    // civil-from-days (Howard Hinnant) — avoids a chrono dependency
    let z = (secs / 86_400) as i64 + 719_468;
    let era = z / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let mo = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = yoe + era * 400 + i64::from(mo <= 2);
    format!("{y:04}-{mo:02}-{d:02}T{h:02}:{m:02}:{s:02}Z")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_in_order_with_header() {
        let out = render(
            "jsdata.cfg",
            &[
                ("B".into(), "{ x: 1 }".into()),
                ("A".into(), "Object.keys(B).length".into()),
            ],
        );
        assert!(out.starts_with("// @generated by jsdata"));
        assert!(out.contains("// config: jsdata.cfg\n"));
        assert!(out.contains("// built: "));
        let b = out.find("export const B = { x: 1 };").unwrap();
        let a = out.find("export const A = Object.keys(B).length;").unwrap();
        assert!(b < a, "config order preserved");
    }

    #[test]
    fn timestamp_ignored_in_diff() {
        let a = "// built: 2026-01-01T00:00:00Z\nexport const X = 1;\n";
        let b = "// built: 2027-12-31T23:59:59Z\nexport const X = 1;\n";
        assert!(same_ignoring_timestamp(a, b));
        assert!(!same_ignoring_timestamp(
            a,
            "// built: x\nexport const X = 2;\n"
        ));
    }

    #[test]
    fn verbatim_body_built_line_still_diffs() {
        let a = "// built: 2026-01-01T00:00:00Z\nexport const X = {\n// built: v1\n};\n";
        let b = "// built: 2027-01-01T00:00:00Z\nexport const X = {\n// built: v2\n};\n";
        assert!(
            !same_ignoring_timestamp(a, b),
            "only the header timestamp is ignorable"
        );
    }

    #[test]
    fn project_iife_wraps_and_returns_all_vars() {
        // rendered as the value of an `export const`, so it must compose with render()
        let iife = render_project_iife(&[
            ("PASSIVES".into(), "{ regen: 1 }".into()),
            ("COUNT".into(), "Object.keys(PASSIVES).length".into()),
        ]);
        let out = render("all.cfg", &[("bp".into(), iife)]);
        assert!(out.contains("export const bp = (() => {\n"), "{out}");
        assert!(out.contains("  const PASSIVES = { regen: 1 };\n"));
        assert!(out.contains("  const COUNT = Object.keys(PASSIVES).length;\n"));
        assert!(
            out.contains("  return { PASSIVES, COUNT };\n})();\n"),
            "{out}"
        );
    }

    #[test]
    fn langs_object_escapes_and_composes() {
        let obj = render_langs_object(&[
            (
                "en_US".into(),
                vec![
                    ("rrs.rarity.common".into(), "§7§lCommon".into()),
                    ("pack.name".into(), "Rarity & \"Stats\"".into()),
                ],
            ),
            ("ar_SA".into(), vec![("pack.name".into(), "الندرة".into())]),
        ]);
        let out = render("all.cfg", &[("langs".into(), obj)]);
        assert!(out.contains("export const langs = {\n"), "{out}");
        assert!(out.contains("  en_US: {\n"));
        assert!(
            out.contains("    \"rrs.rarity.common\": \"§7§lCommon\",\n"),
            "{out}"
        );
        assert!(
            out.contains("    \"pack.name\": \"Rarity & \\\"Stats\\\"\",\n"),
            "{out}"
        );
        assert!(out.contains("  ar_SA: {\n"));
        assert!(out.contains("الندرة"));
        assert!(
            out.trim_end().ends_with("};"),
            "closes as a statement: {out}"
        );
    }

    #[test]
    fn iso_format_sane() {
        let t = now_iso();
        // 2026-07-10T12:34:56Z shape
        assert_eq!(t.len(), 20, "{t}");
        assert_eq!(&t[4..5], "-");
        assert_eq!(&t[10..11], "T");
        assert!(t.ends_with('Z'));
        assert!(t.starts_with("20"));
    }
}
